- name: add apt repo
  apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise main'

- name: add apt key
  apt_key: id="C7917B12" url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xB9316A7BC7917B12"

- name: install packages
  apt: pkg={{item}} state=latest update_cache=true
  environment:
    RUNLEVEL: '1'
  with_items:
    - redis-server
    - redis-tools

- name: stop redis server
  service: name=redis-server state=stopped
