- name: prepare fuse
  shell: touch /dev/fuse creates=/dev/fuse

- name: install fuse
  apt: pkg=fuse state=present

- name: install required packages
  tags: java
  apt: pkg={{item}} state=latest
  with_items:
    - debconf
    - debconf-utils
    - java-common

- name: install openjdk packages
  apt: pkg={{item}} state=latest install_recommends=no
  with_items: java_packages

- name: add webupd8team repo
  apt_repository: repo="ppa:webupd8team/java"

- name: retrieve status of oracle licences
  shell: >
    debconf-get-selections | grep -q {{item}} && echo -n 'yes' || echo -n 'no'
  register: java_license_status
  changed_when: False
  with_items: java_ora_versions

- name: accept oracle licenses
  shell: >
    /bin/echo -e {{item.item}} shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: item.stdout != "yes"
  with_items: java_license_status.results

- name: install oracle versions
  apt: pkg={{item}} state=latest update_cache=yes
  with_items: java_ora_versions

- name: update jdk_switcher repo
  git: repo="git://github.com/michaelklishin/jdk_switcher.git" dest={{jdk_switcher_root}}

- name: copy jdk_switcher to path
  file: dest={{jdk_switcher_bin_path}} src={{jdk_switcher_root}}/jdk_switcher.sh state=link

- name: set default version
  shell: >
    update-java-alternatives -s {{java_default_version}}

