- name: stop dbus-daemon service
  service: name=dbus state=stopped

- name: remove dbus-daemon pid file
  file: path=/var/run/dbus/pid state=absent

- name: clean apt cache
  shell: apt-get -qy clean

- name: autoremove apt packages
  shell: apt-get -qy autoremove
