---
- hosts: all
  tags: nodejs

  tasks:

  - name: nodejs | add apt repo
    apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu precise main' state=present

  - name: nodejs | add apt key
    apt_key: id=C7917B12 url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xB9316A7BC7917B12 state=present

  - name: nodejs | install packages
    apt: pkg=$item state=latest update_cache=true
    with_items:
      - nodejs
