- name: add apt repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian precise contrib'

- name: add apt key
  apt_key: id="A14F4FCA" url="http://packages.erlang-solutions.com/debian/erlang_solutions.asc"

- name: install packages
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
    - erlang-nox
