#
# require packages: python-apt, python-pycurl
#
---
- hosts: all

  tasks:

  - name: postgresql | add apt repo
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

  - name: postgresql | add apt key
    apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: postgresql | install packages
    apt: pkg=$item state=latest update_cache=true
    environment:
      RUNLEVEL: '1'
    with_items:
      - postgresql-${pg_version}
      - postgresql-client-${pg_version}
      - postgresql-contrib-${pg_version}
      - libpq-dev

  - name: postgresql | create pg_hba.conf
    copy: src=files/pg_hba.conf dest=/etc/postgresql/${pg_version}/main/pg_hba.conf

  - name: postgresql | stop postgresql server
    service: name=postgresql state=stopped
