- name: add apt repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main'

- name: add apt key
  apt_key: url="http://www.rabbitmq.com/rabbitmq-signing-key-public.asc"

- name: install packages
  apt: pkg={{item}} state=latest update_cache=true
  environment:
    RUNLEVEL: '1'
  with_items:
    - rabbitmq-server

- name: stop rabbitmq server
  service: name=rabbitmq-server state=stopped
