---
- hosts: all

  roles:
    - bootstrap

    - java
    - rbenv
    - nodejs
    - sbt
    - lein

    - phantomjs

    - postgresql
    - redis
    - mysql
    - rabbitmq
    - elasticsearch

    - services
    - cleanup
