- name: add apt repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: add apt key
  apt_key: id="ACCC4CF8" url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"

- name: install packages
  apt: pkg={{item}} state=latest update_cache=true
  environment:
    RUNLEVEL: '1'
  with_items:
    - postgresql-{{pg_version}}
    - postgresql-client-{{pg_version}}
    - postgresql-contrib-{{pg_version}}
    - libpq-dev

- name: create pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/{{pg_version}}/main/pg_hba.conf

- name: stop postgresql server
  service: name=postgresql state=stopped
